# Default values for supernova.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 0

app:
  buckets:
    url: "http://dev-cdi.xby2-rnd.com/eks/cdi/svc/buckets"
  workflow:
    url: "http://dev-cdi.xby2-rnd.com/eks/cdi/svc/workflow"
    id: 2
  ticker:
    outer: 3000
    inner: 1000

db:
  host: "clinical-integrator.c0r3mfqlrqup.us-east-2.rds.amazonaws.com"
  port: 5432
  user: "postgres"
  password: "Xby235055w12milerd."
  dbname: cdidev

image:
  repository: moohh/lettercounter
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 3001

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host:
      paths: []

  tls: []

resources:
  requests:
    cpu: "150m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}
